### ISSUE TITLE
Add new record Block title errors.

### ISSUE THREAD

**Issue by orbweaver-dev** [agiient/case-management#4]
LBL_BLOCK_GENERAL_INFORMATION and LBL_BLOCK_SYSTEM_INFORMATION under Case Management menu after clicking on create new case in addition to the 'General Information' block. Total of Three (3) blocks now.

**Comment by orbweaver-dev** [comment]
Investigate code to see why the previous correction did not take.

**Comment by orbweaver-dev** [comment]
After several hours and process of elimination, I discovered that I mistakenly edited the block label 'LBL_BLOCK_GENERAL_INFORMATION' without clicking on 'Details' first in version 1.0.0.
Doing this created a new block with the new label, but lost the ability to be edited or deleted and all fields entered at the time of the original creation also lost the ability to be edited or deleted. All created fields remain and cannot be deleted or moved.

**Comment by agiient** [comment]
Uninstalled module to correct this issue.

**Comment by orbweaver-dev** [comment]
Uninstalled module to correct this issue.
